# Generated by Django 5.2.3 on 2025-06-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_hls_playlist_movie_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'Action'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('horror', 'Horror'), ('sci-fi', 'Sci-Fi'), ('documentary', 'Documentary')], default='action', max_length=20),
        ),
    ]
